env:
  global:
    - CC_TEST_REPORTER_ID=ad165e4a8c46703882439e668db63e13a7a9b12ecb2cdc4a884524fb9264a114
language: node_js
node_js:
 - "stable"

cache:
  directories:
    - "node_modules"

addons:
  apt:
    update: true

after_success: npm run coverage