/**
 * @fileOverview - This module holds dummy data for users
 * @exports - users object
 */
const users = [
  {
    id: 1,
    email: 'shonubijerry@gmail.com',
    firstName: 'Shonubi',
    lastName: 'Oluwakorede',
    password: '$2b$10$DAUlN//SebBEPkWppjD1AeIRy6dWJ3k8DMv.T4hBSeZh/Lycb0Yki',
    address: '33, Ahmed Oghere Street, Idimu',
    status: 'verified',
    isAdmin: true,
  },
  {
    id: 2,
    email: 'adenekan2017@gmail.com',
    firstName: 'Adenekan',
    lastName: 'Quadri',
    password: '$2b$10$DAUlN//SebBEPkWppjD1AeIRy6dWJ3k8DMv.T4hBSeZh/Lycb0Yki',
    address: '6, Felix Street, Ikotun',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 3,
    email: 'badmanga@yahoo.com',
    firstName: 'Gbenga',
    lastName: 'Badmus',
    password: '$2b$10$DAUlN//SebBEPkWppjD1AeIRy6dWJ3k8DMv.T4hBSeZh/Lycb0Yki',
    address: '4, Rhodes Crescent, Apapa',
    status: 'unverified',
    isAdmin: false,
  },
  {
    id: 4,
    email: 'chiboy155@gmail.com',
    firstName: 'Chisom',
    lastName: 'Nwosu',
    password: '$2b$10$DAUlN//SebBEPkWppjD1AeIRy6dWJ3k8DMv.T4hBSeZh/Lycb0Yki',
    address: '12, Mukandasi Street, Ago',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 5,
    email: 'shehumohammed@gmail.com',
    firstName: 'Mohammed',
    lastName: 'Shehu',
    password: '$2b$10$DAUlN//SebBEPkWppjD1AeIRy6dWJ3k8DMv.T4hBSeZh/Lycb0Yki',
    address: '17, Fidel Streen, Garki',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 6,
    email: 'mikeo007@gmail.com',
    firstName: 'Mike',
    lastName: 'Ogbuehi',
    password: '$2b$10$DAUlN//SebBEPkWppjD1AeIRy6dWJ3k8DMv.T4hBSeZh/Lycb0Yki',
    address: '9, Ahmed Fashola Street, Yaba',
    status: 'unverified',
    isAdmin: false,
  },
  {
    id: 7,
    email: 'adeade@gmail.com',
    firstName: 'Ade',
    lastName: 'Adebayo',
    password: '$2b$10$DAUlN//SebBEPkWppjD1AeIRy6dWJ3k8DMv.T4hBSeZh/Lycb0Yki',
    address: '5, Adams street, Oshodi',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 8,
    email: 'ciromalapai@hotmail.com',
    firstName: 'Lapai',
    lastName: 'Chiroma',
    password: '$2b$10$DAUlN//SebBEPkWppjD1AeIRy6dWJ3k8DMv.T4hBSeZh/Lycb0Yki',
    address: '17, Bank avenue, Garki',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 9,
    email: 'janetpeters@live.com',
    firstName: 'Janet',
    lastName: 'Peters',
    password: '$2b$10$DAUlN//SebBEPkWppjD1AeIRy6dWJ3k8DMv.T4hBSeZh/Lycb0Yki',
    address: '17, Isaac John street, Ikeja',
    status: 'unverified',
    isAdmin: false,
  },
  {
    id: 10,
    email: 'mamoodd@gmail.com',
    firstName: 'Mamood',
    lastName: 'Daura',
    password: '$2b$10$DAUlN//SebBEPkWppjD1AeIRy6dWJ3k8DMv.T4hBSeZh/Lycb0Yki',
    address: '17, Alhaji Abdulahi street, Kano',
    status: 'unverified',
    isAdmin: false,
  },

];

export default users;
